import json
from deep_translator import GoogleTranslator

# File paths
INPUT_JSON_FILE = 'summarized_article.json'  # JSON file generated by new2.py
OUTPUT_JSON_FILE = 'translated_summarized_articles.json'  # JSON file to store translations

def translate_text(text, dest_language):
    """
    Translate the given text into the specified language using GoogleTranslator.
    """
    try:
        translation = GoogleTranslator(source='auto', target=dest_language).translate(text)
        return translation
    except Exception as e:
        print(f"Error translating text: {e}")
        return None

def translate_article(article):
    """
    Translate the title and summary of an article into Hindi, Marathi, and Gujarati.
    """
    translated_article = {
        "original_title": article["title"],
        "original_summary": article["summary"],
        "translations": {
            "hindi": {
                "title": translate_text(article["title"], "hi"),
                "summary": translate_text(article["summary"], "hi")
            },
            "marathi": {
                "title": translate_text(article["title"], "mr"),
                "summary": translate_text(article["summary"], "mr")
            },
            "gujarati": {
                "title": translate_text(article["title"], "gu"),
                "summary": translate_text(article["summary"], "gu")
            },
            "bengali": {
                "title": translate_text(article["title"], "bn"),
                "summary": translate_text(article["summary"], "bn")
            },
            "tamil": {
                "title": translate_text(article["title"], "ta"),
                "summary": translate_text(article["summary"], "ta")
            },
            "kannada": {
                "title": translate_text(article["title"], "kn"),
                "summary": translate_text(article["summary"], "kn")
            }
        }
    }
    return translated_article

def main():
    # Load articles from the input JSON file
    try:
        with open(INPUT_JSON_FILE, 'r', encoding='utf-8') as f:
            articles = json.load(f)
    except FileNotFoundError:
        print(f"Error: File '{INPUT_JSON_FILE}' not found.")
        return
    except json.JSONDecodeError:
        print(f"Error: File '{INPUT_JSON_FILE}' is not a valid JSON.")
        return

    # Translate each article
    translated_articles = []
    for article in articles:
        print(f"Translating article: {article['title']}")
        translated_article = translate_article(article)
        translated_articles.append(translated_article)

    # Save translated articles to the output JSON file
    with open(OUTPUT_JSON_FILE, 'w', encoding='utf-8') as f:
        json.dump(translated_articles, f, indent=4, ensure_ascii=False)
    
    print(f"Translations saved to '{OUTPUT_JSON_FILE}'.")

# Run the translation script
if __name__ == "__main__":
    main()
